<html>
    <head>
        <link rel="stylesheet" href="globalStyle.css">
        <link rel="icon" href="images/vortexLogo.png">
    </head>
    <title>Vortex - Home</title>
    <body class="default">
        <div class="sticky">
            <a href="index.php" title="Vortex.com" style="margin-left:16px"><img src="images/vortexFullLogo.png" width="16%"></a>
            <form class="inline">
                <input class="searchbar" placeholder="Search">
            </form>
        </div>
        <div class="sidebar">
            <div class="navlink"><a href="index.php">Home</a></div>
            <div class="navlink"><a href="about.php">About Us</a></div>
        </div>
        <div class="body">
            <p class="bodytext">
                Vortex is a video hosting service that provides free entertainment to the public, and allows
                any and all creators to upload videos to the site. Creators, once they gain enough support, can 
                allow advertisers to display short ads on their videos, and recieve a portion of the revenue generated 
                from the adspace sold to advertisers.
            </p>
            <h1>What we do</h1>
            <p class="bodytext">
                Vortex aims to be a platform for others to express their creativity and provide entertainment without limits. 
                The main reason Vortex was created was because most other social media sites started censoring content 
                that the owners didn't agree with. Vortex aims to be different. The only content blocked by Vortex 
                is that which is genuinely harmful, such as explicit content, encouragement or display of elf-harm, 
                and content relating to terrorism. Any other content on the platform is allowed. In addition, 
                most other social media platforms are hostile to their users and creators, taking far more money 
                from ad revenue generated by the creators than is necessary, and making changes that are widely met with 
                hate and dislike. Vortex only takes the minimum amount of revenue from creators necessary to keep supporting 
                the site, as well as paying the developers what they earn. In addition, any changes that affect creators or 
                users are announced weeks before official release, and major creators on the platform are given a vote 
                before and after the feature releases. If a large majority of creators vote against the feature, it will be 
                changed or removed.
            </p>
            <h1>Our Policies</h1>
            <p class="bodytext">[idk put policies here i guess]</p>
            <h1>Contact Us</h1>
            <p class="bodytext">
                Buisness Inquiries: <a href="mailto:buisness@vortex.com">buisness@vortex.com</a>
                <br>
                Mailing address: 1234 S. Buisness Street, Phoenix, AZ
            </p>
        </div>
    </body>
</html>
